### ISSUE TITLE
Object.values is not a function?

### ISSUE THREAD

**Issue by lordmortis** [wwayne/es6-enum#1]
I'm getting `Uncaught TypeError: Object.values is not a function` from Chrome when I initialise the enums

i'm doing that this way:
`const ANSWER_TYPES = Enum('NONE', 'SCALE', 'MULTI_CHOICE');`

**Comment by wwayne** [comment]
Which version of nodejs your are using? Weird...I've used this in my project(nodejs < 1.0).
I will take more testa later

**Comment by wwayne** [comment]
@lordmortis Fixed, but make sure you are using `nodejs >= 4.0.0` or using babel in your project.
